apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: go-web-app
  namespace: flux-system
spec:
  interval: 1m
  path: ./infra
  prune: true
  sourceRef:
    kind: GitRepository
    name: go-helm-source